version: 2.1

description: >
  Runs docs-checking logic for Kurtosis repos

# This information will be displayed in the orb registry and is not mandatory.
display:
  home_url: "https://kurtosistech.com"
  source_url: "https://github.com/kurtosis-tech/kurtosis-docs-checker-orb"

jobs:
  check-docs:
    docker:
      - image: cimg/node:22.7.0
    resource_class: small
    parameters:
      markdown-link-check-config-json:
        default: "{}"
        description: Config JSON passed to markdown-link-check package (see https://www.npmjs.com/package/markdown-link-check for full details)
        type: string
      should-check-changelog:
        default: true
        description: Governs whether the changelog checker would run
        type: boolean
      dir-to-exclude:
        default: ""
        description: Governs whether we should skip some dirs in the link checker
        type: string
    steps:
      - checkout

      # Gotchas I discovered when writing this:
      # - Without the '--no-pager' flag, Git will print "WARNING: Terminal is not fully functional" and not display any output
      # - Circle has no way of getting the PR base branch, so we have to hardcode main :( See: https://ideas.circleci.com/cloud-feature-requests/p/provide-env-variable-for-branch-name-targeted-by-pull-request
      # - The --exit-code flag to git-diff returns 0 on no changes, 1 on changes
      # - We have to use 'origin/main' rather than 'main' because Circle does a shallow checkout, and 'main' gets set to something weird and wrong that makes the check buggy
      # We put this behind a parameter to toggle whether we should run it
      - when:
          condition: <<parameters.should-check-changelog>>
          steps:
            - run: "! git --no-pager diff --exit-code origin/main...HEAD docs/changelog.md"

      - run:
          name: Check links in Markdown docs
          command: |
            set -eou pipefail

            sudo npm cache clean --force
            sudo npm install -g markdown-link-check@3.12.2
            config_filepath="$(mktemp)"
            cat \<< EOF > "${config_filepath}"
            <<parameters.markdown-link-check-config-json>>
            EOF

            # we take out the files in a variable so that set -euo pipefail works
            # we also don't put this in quotes otherwise we get a single line instead of multiple lines with each line being a valid file
            REGEX_EXCLUDE_FILTER="<<parameters.dir-to-exclude>>"
            if [ -z "${REGEX_EXCLUDE_FILTER}" ]; then
              all_files=$(find . -iname '*.md' | sort)
            else
              all_files=$(find . -iname '*.md' | egrep -v "$REGEX_EXCLUDE_FILTER" | sort)
            fi

            has_no_errors=true
            # Inspired by https://github.com/open-telemetry/opentelemetry-collector/pull/1156/files/2244e61f4dd0378deffc00d939edf6f800687dcf
            # the $all_files is intentionally not quoted as we want to keep new line information
            for filepath in $all_files ; do
                markdown-link-check --config "${config_filepath}" -qv "${filepath}" || has_no_errors=false
                # Wait to scan files so that we don't overload github with requests which may result in 429 responses
                sleep 2
            done

            "${has_no_errors}"